---
title: "ANA 515 Week 5"
author: Jun Yong Lee
date: 9/25/2022
output: 
  html_document:
    theme:
     bootswatch: darkly
---
  
```{r, include = FALSE} 
library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r, include = FALSE} 
url1 <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/births/US_births_1994-2003_CDC_NCHS.csv"
births_1 <- read.csv(url1)
url2 <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/births/US_births_2000-2014_SSA.csv"
births_2 <- read.csv(url2)
```

```{r, include = FALSE} 
births_1_upto1999 <- filter(births_1, year<2000)
births <- rbind(births_1_upto1999, births_2)
```

```{r, include = FALSE} 
sum(births[which(births$year=='1994'),5])
sum(births[which(births$year=='1995'),5])
sum(births[which(births$year=='1996'),5])
sum(births[which(births$year=='1997'),5])
sum(births[which(births$year=='1998'),5])
sum(births[which(births$year=='1999'),5])
sum(births[which(births$year=='2000'),5])
sum(births[which(births$year=='2001'),5])
sum(births[which(births$year=='2002'),5])
sum(births[which(births$year=='2003'),5])
sum(births[which(births$year=='2004'),5])
sum(births[which(births$year=='2005'),5])
sum(births[which(births$year=='2006'),5])
sum(births[which(births$year=='2007'),5])
sum(births[which(births$year=='2008'),5])
sum(births[which(births$year=='2009'),5])
sum(births[which(births$year=='2010'),5])
sum(births[which(births$year=='2011'),5])
sum(births[which(births$year=='2012'),5])
sum(births[which(births$year=='2013'),5])
sum(births[which(births$year=='2014'),5])
```

```{r, include = FALSE} 
births_by_year <- data.frame(year = c('1994', '1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014'),
births = c(3952767,3899589,3891494,3880894,3941553,3959417,4149598,4110963,4099313,4163060,4186863,4211941,4335154,4380784,4310737,4190991,4055975,4006908,4000868,3973337,4010532))
```

```{r, echo = FALSE}
births_by_year %>%
  ggplot(aes(x=year, y=births, group = 1)) +
  geom_line( color="#F7360C", size=2, alpha=1, linetype=1) +
  ggtitle("Births in US by Year")
```

The line graph above shows the annual number of births in the US from 1994 to 2014.We can see that the number of births rose dramatically in the early 2000's and hit a peak from 2007-2009

```{r, echo = FALSE}
births %>%  
  ggplot(aes(x=month, y=births))+
  geom_bar(stat = "identity", fill="steelblue", size=10)+
  theme_minimal()+
  ggtitle("Births in Us from 1994 to 2014 by Month")
```

The bar graph above shows the monthly number of births in the US from 1994 to 2014. We can see that the number of births tend to be higher during the summer, around July and August, than the other months.